name: reviewdog
on: [pull_request]
jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Run Credo
          uses: sumup-bank/run-credo@v1
